name: Car Price Bot

on:
  schedule:
    - cron: "0 */6 * * *"   # هر 2 ساعت
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: npm start
